# Generated by Django 3.2.15 on 2022-10-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athenaeum', '0006_auto_20221003_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ispn',
            new_name='isbn',
        ),
    ]
